### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by f3l1x** [Trejjam/ThePay#3]
Hi. Thank you for great library.

I've look at your componette page (https://componette.com/trejjam/thepay/). And section releases is so empty :cry:.

![selection_001](https://cloud.githubusercontent.com/assets/538058/21869489/28528d48-d858-11e6-927f-9d5e1fa92110.png)

You can fix it here on Github. Just follow links on release page (https://github.com/Trejjam/ThePay/releases).

![gcpog7iynn](https://cloud.githubusercontent.com/assets/538058/21869496/2ba409e0-d858-11e6-9901-664b8d71c58d.png)

See ya. :fist_oncoming:

**Comment by Trejjam** [comment]
Thanks, I do not know this.
Now it is [fixed](https://github.com/Trejjam/ThePay/releases)
