### ISSUE TITLE
Compability with php 7.2

### ISSUE THREAD

**Issue by hajek-raven** [Trejjam/ThePay#4]

**Comment by Trejjam** [comment]
Hi, can you submit more info?

We already use it on PHP 7.2

**Comment by hajek-raven** [comment]
There are some incompabilities in Payment and ReturnedPayment.
For example:
`public function setReturnUrl(string $returnUrl, array $params = []) : void`
in `Trejjam\ThePay\Payment` is not compatible with parent class (has more parameters).

**Comment by Trejjam** [comment]
Yes, it has more parameters. But it is not incompatibility on language or parent library level.

This library in master has minimal PHP version 7.1, you can view a valid response here: https://3v4l.org/uD31C

This library is an extension for Nette so this parameter extending allow construct URL in framework way, but it should allow passing valid URL to parent class as well.  
If you think this is not true, feel free to pass some failing examples.
